JavaFruitShopTests
mate-academy/jv-fruit-shop-tests pull request #1014
Opened 2024-08-20 05:02 UTC by VladSlob

2024-08-20 21:11 UTC, sarakhmen requested changes
please add tests for each service and handler

2024-08-22 18:01 UTC, okuzan requested changes
checks failed

2024-08-23 14:12 UTC, okuzan requested changes
Still failed. You can check it locally with `mvn clean package`, please don't re-request review until build passes, if you need any assistance feel free to reach us in the chat

2024-09-24 09:28 UTC, okuzan requested changes
Still failed, please don't resubmit solution until it works, ask for help in the chat if needed

2024-09-26 07:37 UTC, ahoienko requested changes
Very nice, left minor comments

2024-09-26 07:37 UTC, ahoienko commented on pom.xml
> +                                            <minimum>0.70</minimum>
What is the reason for this changes?

2024-09-26 07:37 UTC, ahoienko commented on src/main/java/core/basesyntax/util/impl/FileReaderImpl.java
> +public class FileReaderImpl implements FileReader {
Please add tests for this class

2024-09-26 07:37 UTC, ahoienko commented on src/main/java/core/basesyntax/util/impl/FileWriterImpl.java
> +    public void write(String data, String filePath) {
Please add tests for this class

2024-09-26 07:42 UTC, ahoienko requested changes
/

2024-09-26 10:21 UTC, MentorMateAcademy requested changes
almost done

2024-09-26 10:21 UTC, MentorMateAcademy commented on src/test/java/core/basesyntax/handler/impl/BalanceOperationTest.java
> +        assertEquals(100, fruitStorage.get("banana"));
Save values to constants and reuse it

2024-09-26 10:21 UTC, MentorMateAcademy commented on src/test/java/core/basesyntax/service/impl/ShopServiceImplTest.java
> +        transaction3.setQuantity(30);
you can extract build of list in private method

2024-09-26 10:21 UTC, MentorMateAcademy commented on src/test/java/core/basesyntax/util/impl/FileReaderImplTest.java
> +        Files.write(Paths.get(VALID_FILE_PATH), List.of("test content"));
save strings to constants

2024-09-26 10:21 UTC, MentorMateAcademy commented
![image](https://github.com/user-attachments/assets/3b47dfd9-67d0-4d1b-a0fe-8bf325ae5184)
fix your checks

2024-10-01 07:10 UTC, liliia-ponomarenko requested changes
Your code doesn't compile. I see a call to the getStorage() method in several test classes, but there is no such method in the Storage class. You need to fix the solution so that all CI checks pass before submitting it for review.

2024-10-03 06:42 UTC, liliia-ponomarenko requested changes
Your checks have failed, we can't check your solution until they are all fixed.

2025-05-15 06:36 UTC, closed without merging