covered the service with unit tests
mate-academy/jv-fruit-shop-tests pull request #1016
Opened 2024-08-24 18:10 UTC by NikitaLafinskiy

2024-08-27 21:41 UTC, sarakhmen requested changes
overall good job! Let's fix some mistakes and also add tests for your handlers/strategy

2024-08-27 21:41 UTC, sarakhmen commented on src/test/java/core/basesyntax/dao/FruitDaoImplTest.java
> +public class FruitDaoImplTest {
we don't need to have daos tests in this homework

2024-08-27 21:41 UTC, sarakhmen commented on src/test/java/core/basesyntax/serviceimpl/DataConverterImplTest.java
> +    void convert_validInput_Ok() {
```suggestion
    void convert_validInput_ok() {
```
let's follow our naming convention. This part of a method should start with non-capital letter. Fix in all places

2024-08-27 21:41 UTC, sarakhmen commented on src/test/java/core/basesyntax/serviceimpl/DataConverterImplTest.java
> +                actual.get(FIRST_TRANSACTION_INDEX).getOperation());
have you tested the whole list of results here? Is it possible to validate every list item concisely? What do you need to have implemented to make this process easier?

2024-08-27 21:41 UTC, sarakhmen commented on src/test/java/core/basesyntax/serviceimpl/FileReaderImplTest.java
> +    static void beforeAll() throws IOException {
if you write a file before all tests is it worth removing it after all tests?

2024-08-27 21:41 UTC, sarakhmen commented on src/test/java/core/basesyntax/serviceimpl/FileWriterImplTest.java
> +public class FileWriterImplTest {
don't you need to remove output file after all tests?

2024-08-27 21:41 UTC, sarakhmen commented on src/test/java/core/basesyntax/serviceimpl/ReportServiceImplTest.java
> +    // Do not change, fails when using text blocks due to line separator differences
let's remove redundant comment

2024-08-28 07:50 UTC, NikitaLafinskiy commented
Hey, could the issue here be that the github test environment prohibits writing new files to the machine that it is running on? The code works locally when I run tests with Intellij and mvn clean verify, but here it fails unless the files are already located in the /resources dir in advance

2024-08-28 07:51 UTC, NikitaLafinskiy commented
If I delete all files from the /resources dir and run the tests locally they work as expected as well

2024-08-28 17:33 UTC, okuzan approved these changes
Good job!

2024-08-28 17:33 UTC, okuzan commented on src/test/java/core/basesyntax/serviceimpl/ProcessServiceImplTest.java
> +                    20),
if it doesn't fit in one line, let's import enum constant, because it looks messy

2024-08-28 17:33 UTC, okuzan commented on src/main/java/core/basesyntax/serviceimpl/ReportServiceImpl.java
> +        StringBuilder stringBuilder = new StringBuilder(HEADER);
bad naming, doesn't make code more readable

2025-03-06 14:34 UTC, closed without merging