Wrote tests for the completed task
mate-academy/jv-fruit-shop-tests pull request #1084
Opened 2024-12-11 18:18 UTC by Dimon1888

2024-12-12 08:12 UTC, liliia-ponomarenko requested changes
Good job! Let’s  improve your solution ;)

2024-12-12 08:12 UTC, liliia-ponomarenko commented on src/test/java/core/basesyntax/data/dao/FileReaderImplTest.java
> +
```suggestion
```

2024-12-12 08:12 UTC, liliia-ponomarenko commented on src/test/java/core/basesyntax/data/dao/FileWriterImplTest.java
> +public class FileWriterImplTest {
what are you tested here? reader or writer?

2024-12-12 08:12 UTC, liliia-ponomarenko commented on src/test/java/core/basesyntax/data/impl/DataConverterImplTest.java
> +        NumberFormatException exception = assertThrows(NumberFormatException.class,
Did you expect this exception in your solution? Don’t test unchecked exceptions or provide such logic.

2024-12-12 08:12 UTC, liliia-ponomarenko commented on src/test/java/core/basesyntax/data/impl/DataConverterImplTest.java
> +        assertThrows(IllegalArgumentException.class,
the same

2024-12-12 08:12 UTC, liliia-ponomarenko commented on src/test/java/core/basesyntax/data/impl/ShopServiceImplTest.java
> +        OperationException exception = assertThrows(OperationException.class,
why you can’t  supply  fruit if it doesn't  exist in the storage

2024-12-12 08:12 UTC, liliia-ponomarenko commented on src/test/java/core/basesyntax/data/impl/ShopServiceImplTest.java
> +        OperationException exception = assertThrows(OperationException.class,
the same

2024-12-17 13:54 UTC, sarakhmen requested changes
let's improve your solution :)

2025-06-30 07:17 UTC, liliia-ponomarenko requested changes
Let's fix all previous comments ;)

2025-06-30 07:17 UTC, liliia-ponomarenko commented on src/test/java/core/basesyntax/data/dao/FileReaderImplTest.java
> +        String nonExistentPath = "nonExistent" + System.nanoTime() + ".csv";
better expected data 
```suggestion
        String nonExistentPath = "nonExistent" + ".csv";
```

2025-06-30 07:17 UTC, liliia-ponomarenko commented on src/main/java/core/basesyntax/data/dao/FileWriterImpl.java
> +        return null;
Why do you return null?

2025-06-30 07:17 UTC, liliia-ponomarenko commented on src/test/java/core/basesyntax/data/dao/FileWriterImplTest.java
> +        assertThrows(NullPointerException.class,
Do you have such a check in your solution? Don't test system exception

2025-06-30 07:17 UTC, liliia-ponomarenko commented on src/test/java/core/basesyntax/data/impl/DataConverterImplTest.java
> +        assertEquals(QUANTITY, operations.get(FORTH_INDEX).getQuantity());
Simplify it. compare collection

2025-06-30 07:17 UTC, liliia-ponomarenko commented on src/test/java/core/basesyntax/data/impl/DataConverterImplTest.java
> +        NumberFormatException exception = assertThrows(NumberFormatException.class,
not fixed. If you have any questions. Let's discuss it in the chat

2025-06-30 07:17 UTC, liliia-ponomarenko commented on src/test/java/core/basesyntax/data/impl/ShopServiceImplTest.java
> +        OperationException exception = assertThrows(OperationException.class,
not fixed

2026-04-19 09:55 UTC, fetis-off requested changes
Please, check out previous comments and fix it.

2026-04-19 09:55 UTC, fetis-off commented on src/test/java/core/basesyntax/data/dao/FileWriterImplTest.java
> +public class FileWriterImplTest {
I am wondering where is the successful cases in your test class?

2026-04-19 09:55 UTC, fetis-off commented on src/test/java/core/basesyntax/data/impl/DataConverterImplTest.java
> +        assertEquals(QUANTITY, operations.get(FORTH_INDEX).getQuantity());
simplify it. This chain of assertions looks weird

2026-04-19 09:55 UTC, fetis-off commented on src/test/java/core/basesyntax/data/impl/DataConverterImplTest.java
> +        NumberFormatException exception = assertThrows(NumberFormatException.class,
Not fixed yet

2026-04-20 04:02 UTC, Dimon1888 commented on src/test/java/core/basesyntax/data/impl/DataConverterImplTest.java
> +        NumberFormatException exception = assertThrows(NumberFormatException.class,
Справа  в тому що це старий код а я написав новий , запушив але ви його не бачите, аналізуєте старі помилки 
як це виправити?????

2026-04-22 04:01 UTC, closed without merging