Tests created
mate-academy/jv-fruit-shop-tests pull request #185
Opened 2022-01-30 14:28 UTC by StanislavSonich

2022-02-02 11:41 UTC, MaliukDaria requested changes

2022-02-02 11:41 UTC, MaliukDaria commented on src/test/java/core/basesyntax/service/impl/OperationStrategyImplTest.java
> +    @Test(expected = NullPointerException.class)
а что касательно этого комментария?

2022-02-10 09:26 UTC, Resci requested changes
Коли ментор залишає коментар, це означає що до нього потрібно прислухатися, зрозуміти з якою метою він був залишений і виправити. Я погоджуюся з коментарем. Варто змінити логіку методу і в тесті очікувати іншу помилку замість того, щоб просто прибрати неправильний тест
![image](https://user-images.githubusercontent.com/49445891/153376669-bd885a73-8b15-41eb-b574-28989b25c2a4.png)
![image](https://user-images.githubusercontent.com/49445891/153376797-f3c9c563-a1a6-4eca-83c8-c4871200ed36.png)

2022-02-10 09:26 UTC, Resci commented on src/main/java/core/basesyntax/service/impl/OperationStrategyImpl.java
> +    public void getOperationHandler() {
Навіщо нам цей метод?

2022-02-14 11:08 UTC, Resci requested changes

2022-02-14 11:08 UTC, Resci commented on src/main/java/core/basesyntax/strategy/PurchaseOperationHandler.java
> +    public Map<String, OperationHandler> getOperationHandlerMap(Locale a) {
Навіщо нам цей метод?

2022-02-14 11:08 UTC, Resci commented on src/test/java/core/basesyntax/service/impl/OperationStrategyImplTest.java
> +    }
Що перевіряє цей тест?

2022-02-14 11:08 UTC, Resci commented on src/test/java/core/basesyntax/service/impl/OperationStrategyImplTest.java
> +    public void getOperationHandler_wrongOperationL_notOk() throws Exception {
Що перевіряє цей тест?

2022-02-22 23:02 UTC, closed without merging