Wrote Tests to FruitShop
mate-academy/jv-fruit-shop-tests pull request #200
Opened 2022-02-21 14:56 UTC by dima-semeniuk

2022-02-21 19:30 UTC, nastyaprokhorenko commented on src/test/java/core/basesyntax/database/StorageDaoImplTest.java
> +
empty line

2022-02-21 19:30 UTC, nastyaprokhorenko commented on src/test/java/core/basesyntax/database/StorageDaoImplTest.java
> +    public void fruit_add_ok() {
test method name should look like this: methodName_state_expectedBehavior
```suggestion
    public void add_correctFruitName_ok() {
```

2022-02-21 19:30 UTC, nastyaprokhorenko commented on src/test/java/core/basesyntax/model/FruitTransactionTest.java
> +
empty line

2022-02-21 19:30 UTC, nastyaprokhorenko commented on src/test/java/core/basesyntax/service/impl/WriterToCsvTest.java
> +            actual = Files.readAllLines(Path.of(FILE)).stream()
not sure if it is correct to read the file in the test method

2022-02-21 19:30 UTC, nastyaprokhorenko commented on src/test/java/core/basesyntax/database/StorageDaoImplTest.java
> +    public void fruit_add_notOk() {
```suggestion
    public void add_existingFruit_notOk() {
```

2022-02-21 19:30 UTC, nastyaprokhorenko commented on src/test/java/core/basesyntax/database/StorageDaoImplTest.java
> +    public void fruit_get_ok() {
let's rename all test methods

2022-02-21 19:48 UTC, nastyaprokhorenko approved these changes
looks good to me!

2022-02-22 11:11 UTC, KostyaNikiforov requested changes

2022-02-22 11:11 UTC, KostyaNikiforov commented on src/main/java/core/basesyntax/database/Storage.java
> +
Empty line

2022-02-22 11:11 UTC, KostyaNikiforov commented on src/test/java/core/basesyntax/database/StorageDaoImplTest.java
> +    }
Better move this method to the end of the class

2022-02-22 11:11 UTC, KostyaNikiforov commented on src/test/java/core/basesyntax/database/StorageDaoImplTest.java
> +    public void addFruit_ok() {
```suggestion
    public void add_fruit_ok() {
```
And everywhere below

2022-02-22 11:11 UTC, KostyaNikiforov commented on src/test/java/core/basesyntax/database/StorageDaoImplTest.java
> +        storageDao.add(fruit);
```suggestion
        Storage.fruits.add(fruit);
```
Ты ожидаешь ошибку при вызове второго метода, а этой строчкой ты только создаёшь необходимые условия для тестирования, поэтому лучше обращаться к storage напрямую

2022-02-22 11:11 UTC, KostyaNikiforov commented on src/test/java/core/basesyntax/model/FruitTransactionTest.java
> +public class FruitTransactionTest {
There is no need to test dto objects

2022-02-22 11:11 UTC, KostyaNikiforov commented on src/test/java/core/basesyntax/service/impl/ReaderFromCsvTest.java
> +        Assert.assertEquals(ROWS_IN_FILE, actual.size());
Why don't compare the actual data with expected from DATA constant?

2022-02-22 11:11 UTC, KostyaNikiforov commented on src/test/java/core/basesyntax/service/impl/ReportCreatorImplTest.java
> +    public void setUp() throws Exception {
```suggestion
    public void setUp() {
```

2022-02-22 11:11 UTC, KostyaNikiforov commented on src/test/java/core/basesyntax/service/impl/ReportCreatorImplTest.java
> +    public void tearDown() throws Exception {
```suggestion
    public void tearDown() {
```
And better move this method to the end of the file

2022-02-22 11:11 UTC, KostyaNikiforov commented on src/test/java/core/basesyntax/strategy/impl/SupplyOperationHandlerTest.java
> +    public void setUp() throws Exception {
```suggestion
    public void setUp() {
```

2022-02-22 13:03 UTC, KostyaNikiforov approved these changes

2022-02-23 10:25 UTC, boroda4436 approved these changes

2023-10-23 11:29 UTC, closed without merging