Jv hw fruit shop tests
mate-academy/jv-fruit-shop-tests pull request #223
Opened 2022-04-12 12:12 UTC by VitaliiBozadzhy88

2022-04-12 15:51 UTC, Nick97-git requested changes

2022-04-12 16:05 UTC, Nick97-git commented on src/test/java/service/ReportCreatorImplTest.java
> +        FruitTransaction secondFruitTransaction;
you missed this one

2022-04-12 16:06 UTC, Nick97-git commented on src/test/java/service/WriterImplTest.java
> +    private static final String INVALID_PATH = "";
this comment considered only INVALID_PATH, everything else should be returned

2022-04-12 16:06 UTC, Nick97-git requested changes
left comments under the comments from my previous review

2022-04-13 00:51 UTC, VitaliiBozadzhy88 commented on src/test/java/service/ReportCreatorImplTest.java
> +        FruitTransaction secondFruitTransaction;
Sorry, I missed this. 
I can't understand what exactly I have to do?

2022-04-13 10:09 UTC, Nick97-git requested changes

2022-04-13 10:09 UTC, Nick97-git commented on src/test/java/service/ReportCreatorImplTest.java
> +
remove empty line

2022-04-13 10:09 UTC, Nick97-git commented on src/test/java/service/ReportCreatorImplTest.java
> +    private final FruitTransaction fruitTransaction = new FruitTransaction();
make them local

2022-04-13 10:09 UTC, Nick97-git commented on src/test/java/service/ReportCreatorImplTest.java
> +        secondFruitTransaction.setFruit("apple");
I meant to create such private method: 
private FruitTransaction(String fruit, int quantity) {
        FruitTransaction fruitTransaction = new FruitTransaction();
        fruitTransaction.setFruit(fruit);
        fruitTransaction.setQuantity(quantity);
       return fruitTransaction;
}

2022-04-16 19:11 UTC, VitaliiBozadzhy88 commented on src/test/java/service/ReportCreatorImplTest.java
> +        secondFruitTransaction.setFruit("apple");
I understand what exactly you want, but at the same time I need your help to understand in what way I can decide it. So show me please and tech me please what you want from this piece of code. Great thanks

2022-04-20 12:09 UTC, MaliukDaria commented on src/test/java/service/FruitParserImplTest.java
> +    @Test(expected = NullPointerException.class)
It strange to expect NPE, lets throw some RuntimeException instead of NPE

2022-04-20 12:19 UTC, MaliukDaria commented on src/test/java/service/ReportCreatorImplTest.java
> +        secondFruitTransaction.setFruit("apple");
Мається на увазі щось таке:
```
public class ReportCreatorImplTest {
    @Test
    public void createReport_Ok() {
        List<FruitTransaction> transactions = List.of(
                getFruitTransaction("banana", 172),
                getFruitTransaction("banana", 172),
                getFruitTransaction("apple", 190)
        );

        List<FruitTransaction> cleanListWithoutDuplicates = transactions.stream()
                .distinct().collect(Collectors.toList());

        String expected = "fruit,quantity"
                + System.lineSeparator()
                + "banana,172"
                + System.lineSeparator()
                + "apple,190"
                + System.lineSeparator();
        ReportCreator reportCreator = new ReportCreatorImpl();
        String actual = reportCreator.createReport(cleanListWithoutDuplicates);

        Assert.assertEquals(expected, actual);
    }

    private FruitTransaction getFruitTransaction(String fruit, int quantity) {
        FruitTransaction fruitTransaction = new FruitTransaction();
        fruitTransaction.setFruit(fruit);
        fruitTransaction.setQuantity(quantity);
        return fruitTransaction;
    }
}
```

2022-04-20 18:01 UTC, closed without merging