Tests implemented
mate-academy/jv-fruit-shop-tests pull request #337
Opened 2022-08-27 14:43 UTC by SpaceUrgent

2022-08-27 17:14 UTC, kozhukhovsky requested changes
Before you create PR with your homework, you need to go through the checklist under the task and correct all the points described there. The mentor will not check the work until the checklist points are corrected

2022-08-27 17:14 UTC, kozhukhovsky commented on src/test/java/core/basesyntax/ShopServiceImplTest.java
> +            assertEquals(Integer.valueOf(i), storageDao.getQuantity("Fruit " + i));
![image](https://user-images.githubusercontent.com/12864128/187040891-d923e7df-0495-4517-afa0-e641c164b33c.png)

2022-08-28 07:25 UTC, aaananas requested changes

2022-08-28 07:25 UTC, aaananas commented on src/test/java/core/basesyntax/FileReaderImplTest.java
> +        }
```suggestion
        assertEquals(expected, actual);
```
two lists are equal if they have the same elements in the same order

2022-08-28 07:25 UTC, aaananas commented on src/test/java/core/basesyntax/FileReaderImplTest.java
> +        }
create String value, that contains expected value, or do it like you did before - create a file to compare

2022-08-28 07:25 UTC, aaananas commented on src/test/java/core/basesyntax/FileWriterImplTest.java
> +        file.delete();
rather create a global variable File file and delete it here.

2022-08-28 07:25 UTC, aaananas commented on src/test/java/core/basesyntax/FileWriterImplTest.java
> +        assertEquals(THIRD_REPORT, actual);
```suggestion
        fileWriter.writeReport(FIRST_REPORT_PATH, FIRST_REPORT);
        String actual = readFile(FIRST_REPORT_PATH);
        File file = new File(FIRST_REPORT_PATH);
        assertTrue(file.exists());
        assertEquals(FIRST_REPORT, actual);
```
no need to duplicate

2022-08-28 07:25 UTC, aaananas commented on src/test/java/core/basesyntax/OperationHandlerImplTest.java
> +    private OperationHandler operationHandler;
```suggestion
    private OperationHandler balanceHandler;
    private OperationHandler increaseHandler;
    private OperationHandler decreaseHandler;
```
you can move handlers here, and initialize them in @Before method, use each handler whereever you need

2022-08-28 07:25 UTC, aaananas commented on src/test/java/core/basesyntax/OperationHandlerImplTest.java
> +            operationHandler.handle(new FruitTransaction(BALANCE, "Fruit " + i, i));
```suggestion
        for (int i = 0; i < 10; i++) {
            balanceHandler.handle(new FruitTransaction(BALANCE, "Fruit " + i, i));
```

2022-08-28 07:25 UTC, aaananas commented on src/test/java/core/basesyntax/OperationHandlerImplTest.java
> +        }
```suggestion
        Storage.storage.put("apple", 10);
        Storage.storage.put("banana", 20);
        Storage.storage.put("mango", 30);
        for (int i = 0; i < 10; i++) {
            decreaseHandler.handle(new FruitTransaction(PURCHASE, "apple", 1));
            decreaseHandler.handle(new FruitTransaction(PURCHASE, "banana", 1));
            decreaseHandler.handle(new FruitTransaction(PURCHASE, "mango", 1));
        }
```

2022-08-28 07:25 UTC, aaananas commented on src/test/java/core/basesyntax/OperationHandlerImplTest.java
> +        }
```suggestion
        Storage.storage.put("apple", 10);
        Storage.storage.put("banana", 20);
        Storage.storage.put("mango", 30);
        for (int i = 0; i < 10; i++) {
            increaseHandler.handle(new FruitTransaction(SUPPLY, "apple", 1));
            increaseHandler.handle(new FruitTransaction(RETURN, "banana", 1));
            increaseHandler.handle(new FruitTransaction(SUPPLY, "mango", 1));
        }
```

2022-08-28 07:25 UTC, aaananas commented on src/test/java/core/basesyntax/OperationHandlerImplTest.java
> +
```suggestion
```

2022-08-28 07:25 UTC, aaananas commented on src/test/java/core/basesyntax/FileReaderImplTest.java
> +    public void readEmptyFromFile_ok() {
![image](https://user-images.githubusercontent.com/81781479/187062873-109a5609-25aa-4558-afb7-ad53219fce0a.png)
change all your test method names accordingly to this pattern

2022-08-28 15:10 UTC, zachar-chorny requested changes

2022-08-28 15:10 UTC, zachar-chorny commented on src/test/java/core/basesyntax/FileReaderImplTest.java
> +    public void readFile_ok() {
Not the full name of the method, you have to stick to that naming:
<img width="343" alt="Screen Shot 2022-08-28 at 6 03 17 PM" src="https://user-images.githubusercontent.com/90692308/187080761-85dcb9e6-1e58-46ac-bfe2-194ac23198dd.png">

2022-08-28 15:10 UTC, zachar-chorny commented on src/test/java/core/basesyntax/FileWriterImplTest.java
> +    public void writeReport_ToFile_ok() {
```suggestion
    public void writeReport_ExistInput_ok() {
```
the second parameter is a statement, correct the names everywhere

2022-08-28 15:10 UTC, zachar-chorny commented on src/test/java/core/basesyntax/OperationStrategyImplTest.java
> +    public void get_ok() {
naming!

2022-08-28 15:10 UTC, zachar-chorny commented on src/test/java/core/basesyntax/ReportCreatorImplTest.java
> +    public void createReport_ok() {
naming!

2022-08-28 15:10 UTC, zachar-chorny commented on src/test/java/core/basesyntax/ReportCreatorImplTest.java
> +        assertEquals(EXPECTED_SECOND_REPORT, report);
```suggestion
        String report = reportCreator.createReport(balances);
        assertEquals(EXPECTED_FIRST_REPORT, report);
```

2022-08-28 15:10 UTC, zachar-chorny commented on src/test/java/core/basesyntax/ShopServiceImplTest.java
> +    public void getBalance_ok() {
naming

2022-08-28 15:10 UTC, zachar-chorny commented on src/test/java/core/basesyntax/StorageDaoImplTest.java
> +    public void saveGet_ok() {
naming

2022-08-28 15:10 UTC, zachar-chorny commented on src/test/java/core/basesyntax/TransactionParserImplTest.java
> +    public void parseEmpty_ok() {
naming

2022-08-28 15:10 UTC, zachar-chorny commented on src/test/java/core/basesyntax/TransactionParserImplTest.java
> +    public void parse_ok() {
naming

2022-08-29 17:29 UTC, aaananas approved these changes

2025-03-09 18:13 UTC, closed without merging