100% test's coverage
mate-academy/jv-fruit-shop-tests pull request #382
Opened 2022-09-02 11:13 UTC by Rossoline

2022-09-02 11:36 UTC, Maksym-Korkosh approved these changes

2022-09-03 16:00 UTC, KseniiaMakarova requested changes

2022-09-03 16:00 UTC, KseniiaMakarova commented on src/test/java/core/basesyntax/strategy/handler/SupplyOperationHandlerTest.java
> +        supplyOperationHandler.apply(new Transaction("b", banana, 15));
why b?

2022-09-03 16:00 UTC, KseniiaMakarova commented on src/test/java/core/basesyntax/strategy/handler/PurchaseOperationHandlerTest.java
> +    public void apply_PurchaseMoreThanBalance_ThrowException_ok() {
```suggestion
    public void apply_PurchaseMoreThanBalance_ThrowException() {
```

2022-09-03 17:00 UTC, KseniiaMakarova approved these changes

2026-03-29 17:38 UTC, closed without merging