Migrate to junit5
mate-academy/jv-fruit-shop-tests pull request #606
Opened 2023-04-03 14:47 UTC by nacenik

2023-04-03 15:26 UTC, hronograf requested changes

2023-04-03 15:36 UTC, nacenik commented on pom.xml
> +            <version>${junit.jupiter.version}</version>
[Here is test PR](https://github.com/mate-academy/jv-fruit-shop-tests/pull/607)
Everything is working

2023-04-03 17:35 UTC, hronograf commented on pom.xml
> +            <version>${junit.jupiter.version}</version>
great, thanks

2023-04-04 05:51 UTC, boroda4436 commented on pom.xml
> +            <version>${junit.jupiter.version}</version>
<img width="326" alt="image" src="https://user-images.githubusercontent.com/13794896/229699520-67e895db-312c-4df2-8880-0e8ba540db71.png">
these dependencies are from JUnit 4

2023-04-04 06:41 UTC, boroda4436 approved these changes

2023-04-04 12:15 UTC, merged