HW-jv-fruit-shop-tests-22-Of-May
mate-academy/jv-fruit-shop-tests pull request #632
Opened 2023-05-22 13:57 UTC by ViktoriiaSvidovska

2023-05-22 14:50 UTC, aaananas commented on src/test/java/core/basesyntax/service/CsvFileReaderServiceImplTest.java
> +        Assertions.assertThrows(NullPointerException.class, () ->
you should not expect NPE, remove this test

2023-05-22 14:51 UTC, aaananas commented on src/test/java/core/basesyntax/service/CsvFileReaderServiceImplTest.java
> +    public void readDataFromFile_isOk() {
follow a pattern when naming your test methods
```<method name>_<short description>_<expected behavior>()```

2023-05-22 14:53 UTC, aaananas commented on src/test/java/core/basesyntax/service/CsvFileReportServiceImplTest.java
> +public class CsvFileReportServiceImplTest {
<img width="1091" alt="image" src="https://github.com/mate-academy/jv-fruit-shop-tests/assets/81781479/9b294e0c-c302-4b9b-8cd0-8614fd320186">

2023-05-24 16:53 UTC, andriy-shulepa requested changes

2023-05-24 16:53 UTC, andriy-shulepa commented on src/test/java/core/basesyntax/service/CsvFileReaderServiceImplTest.java
> +                fileCopyPath, StandardCopyOption.REPLACE_EXISTING);
you don't need to copy files. you created test file and you should use it. The problem is that you hardcoded path to your config inside ConfigReader. do refactoring so you will have separate configs for main code and for the test code

2023-05-24 16:53 UTC, andriy-shulepa commented on src/test/java/core/basesyntax/service/CsvFileWriterServiceImplTest.java
> +        Files.copy(Path.of(configReader.getValueByKey("file.read.from")),
same comment as for reader service

2023-05-25 10:19 UTC, Rommelua requested changes

2023-05-25 10:19 UTC, Rommelua commented on src/test/java/core/basesyntax/service/CsvFileWriterServiceImplTest.java
> +        return csvFileReportService.createReport(allFruits);
Why do you need this stuff here? Simple hardcode String with a few lines.

2023-05-25 10:19 UTC, Rommelua commented on src/test/java/core/basesyntax/service/CsvFileWriterServiceImplTest.java
> +        Assertions.assertTrue(Files.exists(testReportPath), "The file doesn't exist");
I do not see the call to `writeDataToFile()` in this test.

2023-05-25 10:19 UTC, Rommelua commented on src/test/java/core/basesyntax/service/CsvFileWriterServiceImplTest.java
> +                        randomDataGenerator.generateRandomData()),
```suggestion
                       "test data"),
```
Remember KISS principle.

2023-05-25 10:19 UTC, Rommelua commented on src/test/java/core/basesyntax/service/CsvFileWriterServiceImplTest.java
> +                        null),
You should have a valid path when testing null data.

2023-05-26 10:10 UTC, olekskov approved these changes
Good job

2023-10-18 14:57 UTC, closed without merging