Add some checks to project and cover all services with tests
mate-academy/jv-fruit-shop-tests pull request #715
Opened 2023-08-03 07:01 UTC by Denis-Balako

2023-08-03 16:27 UTC, AntonZhdanov approved these changes

2023-08-04 14:15 UTC, andrii-hoienko requested changes
Good, but let`s improve your solution

2023-08-04 14:15 UTC, andrii-hoienko commented on src/test/java/core/basesyntax/operation/BalanceOperationHandlerTest.java
> +    @AfterEach
What if on the moment of first test storage is filled by some data?

2023-08-04 14:15 UTC, andrii-hoienko commented on src/test/java/core/basesyntax/operation/PurchaseOperationHandlerTest.java
> +        Assertions.assertEquals(expected, actual);
Please use static import

2023-08-04 14:15 UTC, andrii-hoienko commented on src/test/java/core/basesyntax/operation/PurchaseOperationHandlerTest.java
> +        Storage.STORAGE.put(VALID_FRUIT_NAME, VALID_FRUIT_AMOUNT);
better to make test in this way: 1.Precondition 2. Executioin 3. Assertions. And each step separate by empty line

2023-08-04 14:15 UTC, andrii-hoienko commented on src/test/java/core/basesyntax/operation/ReturnOperationHandlerTest.java
> +public class ReturnOperationHandlerTest {
There are if in ReturnOperationHandler  it means at least 2 test should be

2023-08-04 14:15 UTC, andrii-hoienko commented on src/test/java/core/basesyntax/operation/SupplyOperationHandlerTest.java
> +public class SupplyOperationHandlerTest {
There are if in ReturnOperationHandler it means at least 2 test should be

2023-08-04 14:15 UTC, andrii-hoienko commented on src/test/java/core/basesyntax/service/CsvWriterServiceTest.java
> +    private static final String VALID_OUTPUT_PATH = "src/test/resources/validTestReport.csv";
What if path is invalid?

2023-08-07 08:24 UTC, Vasul-Pankiv approved these changes

2026-05-02 16:40 UTC, closed without merging