Add test to Fruit Shop
mate-academy/jv-fruit-shop-tests pull request #717
Opened 2023-08-03 12:37 UTC by OlegStashkiv

2023-08-04 08:00 UTC, ivan0dyatlyukkk requested changes
Nice solution! However, I found some issues, so let's look at them, and I will check it one more time :)

2023-08-04 10:26 UTC, ivan0dyatlyukkk approved these changes

2023-08-04 15:52 UTC, vovasalyha requested changes
Good, but let's improve it a bit. Comment about empty lines between logical parts of test method (setup logic, execution and assertion) should be applied to all test methods

2023-08-04 15:52 UTC, vovasalyha commented on src/test/java/core/basesyntax/handlers/BalanceHandlerTest.java
> +        balanceHandler = new BalanceHandler();
Why do you need new instance of the handler for every test?

2023-08-04 15:52 UTC, vovasalyha commented on src/test/java/core/basesyntax/handlers/BalanceHandlerTest.java
> +        balanceHandler.handle(FRUIT_NAME, CORRECT_QUANTITY);
Please, add empty lines between logical parts of the test method (setup logic, executions, assertions)

2023-08-04 15:52 UTC, vovasalyha commented on src/test/java/core/basesyntax/service/implemantation/ReportWriterImplTest.java
> +class ReportWriterImplTest {
Add a test case which checks edge case.

2023-08-04 15:52 UTC, vovasalyha commented on src/test/java/core/basesyntax/service/implemantation/TransactionExecutorImplTest.java
> +    void processDate_correctExecutor_ok() {
You don't need to test your strategy methods in this service, 1 operation just to check if service calls handlers correctly is enough.
![image](https://github.com/mate-academy/jv-fruit-shop-tests/assets/82539553/3c92ae5a-d7b8-49bc-a8d9-5c64253df31f)

2023-08-07 15:23 UTC, Vasul-Pankiv approved these changes

2026-05-21 08:02 UTC, closed without merging