JV-Fruit-shop-tests solution:
mate-academy/jv-fruit-shop-tests pull request #76
Opened 2021-07-13 21:38 UTC by olekskov

- Implemented tests for each public method
- Tests were split to related classes (except handlers that were included into strategy)

2021-07-14 07:12 UTC, RomanDubovskyi requested changes

2021-07-14 07:12 UTC, RomanDubovskyi commented on src/test/java/core/basesyntax/FruitShopServiceImplTest.java
> +    private static final ReportsDao DAO = new ReportsDaoImpl();
```suggestion
    private static final ReportsDao reportsDao = new ReportsDaoImpl();
```
для не immutable класів юзай ловеркейс 
https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names

2021-07-14 07:12 UTC, RomanDubovskyi commented on src/test/java/core/basesyntax/FruitShopServiceImplTest.java
> +        OPERATION_HANDLER_MAP.put(SUPPLY_OPERATION, new SupplyOperationHandler());
таку штуку краще одразу закидувати в метод з аннотацією Before / BeforeAll, так як при додаванні ще тестів в них логіка ініціалізації буде повторюватись + для читаймості краще теж це розділити

2021-07-14 07:12 UTC, RomanDubovskyi commented on src/test/java/core/basesyntax/FruitShopServiceImplTest.java
> +            System.out.println("Report file wasn't deleted before test, reason: " + e);
замість SOUT використовуй меседжі у assert

2021-07-14 07:12 UTC, RomanDubovskyi commented on src/test/java/core/basesyntax/FruitShopServiceImplTest.java
> +            System.out.println("Previous report file wasn't deleted as it's absent but it's ok");
якщо тут ти затираєш файл після виконання тесту, то просто винеси цю логіку в метод After / AfterAll

2021-07-14 07:12 UTC, RomanDubovskyi commented on src/test/java/core/basesyntax/RecordsDaoImplTest.java
> +    //private static final String UNRECORDABLE_FILE = TESTS_FILES_FOLDER + "unrecordableFile.csv";
в ПР не повинно бути закоментованого коду, це погана практика, так як при розробці софту такий код потім забувається і засмічує проект

2021-07-14 07:12 UTC, RomanDubovskyi commented on src/test/java/core/basesyntax/RecordsDaoImplTest.java
> +    /* Method below commented out as file read-only access is now working on Travis side
не зовсім зрозумів цього коменту

2021-07-14 07:12 UTC, RomanDubovskyi commented on src/test/java/core/basesyntax/RecordsDaoImplTest.java
> +        MAP.clear();
аналогічно тут з clear

2021-07-14 20:55 UTC, olekskov commented
Спасибо за ревью, исправил ошибки.
По закомментированнуму тесту - создал файл и выставил в Windows ему read-only права для проверки на выдачу корректного Exception при попытке записи в него. У меня тест работал ок, но Travis в полученный файл смог провести запись и соответственно не получал желаемого Exception и считал тест провальным. 
На досуге поищу как корректно создавать read-only файл для кроссплатформы.

2021-07-15 07:20 UTC, RomanDubovskyi approved these changes

2021-07-15 07:20 UTC, RomanDubovskyi commented on src/test/java/core/basesyntax/FruitShopServiceImplTest.java
> +        operationHandlersMap.put(balanceOperation, new BalanceOperationHandler());
```suggestion
        operationHandlersMap.put(Record.OperationType.BALANCE, new BalanceOperationHandler());
```
можна було одразу так ініціалізувати для зменшення коду

2021-07-15 07:21 UTC, RomanDubovskyi approved these changes

2023-08-29 09:35 UTC, closed without merging