Added some custom exceptions to be used in services. Added @Override …
mate-academy/jv-fruit-shop-tests pull request #868
Opened 2023-12-09 03:55 UTC by ivanlavrinenko

…of equals method in StorageImpl.

Tested handlers and services.

2023-12-09 16:31 UTC, olekskov requested changes
Build is failed. Please recheck your test cases
Probably problem is in a way you write path, like
String path = "src\\test\\resources\\report.csv";
I don't think it should work with double \\

2023-12-09 20:17 UTC, ivanlavrinenko commented
> Build is failed. Please recheck your test cases Probably problem is in a way you write path, like String path = "src\ \test\ \resources\ \report.csv"; I don't think it should work with double \ \

i have build succes in my project, i've also tried to deal with single \ and it gives a compiler error

2023-12-11 09:46 UTC, Sanderfuck requested changes
Make mini refactor of constants

2023-12-11 09:46 UTC, Sanderfuck commented on src/test/java/core/basesyntax/BalanceOperationHandlerTest.java
> +        expectedStorage.put("orange", 888);
Save this to constant and use them

2023-12-11 09:46 UTC, Sanderfuck commented on src/test/java/core/basesyntax/CsvFileWriterServiceTest.java
> +        String path = "shos/neponiatne";
)))

2023-12-11 09:46 UTC, Sanderfuck commented on src/test/java/core/basesyntax/CsvFileWriterServiceTest.java
> +        String path = "src/test/resources/report.csv";
Path can save to constant

2023-12-11 09:46 UTC, Sanderfuck commented on src/test/java/core/basesyntax/PurchaseOperationHandlerTest.java
> +        storage.put("apple", 327);
Constants

2023-12-11 09:46 UTC, Sanderfuck commented on src/test/java/core/basesyntax/ReturnOperationHandlerTest.java
> +        storage.put("apple", 327);
Fix it for all

2023-12-12 12:45 UTC, okuzan requested changes
Separate test classes into the same folder hierarchy as in `main` package

2023-12-12 12:45 UTC, okuzan commented on src/test/java/core/basesyntax/ReportServiceTest.java
> +    public static void setReportService() {
```suggestion
    public static void init() {
```

2023-12-12 12:45 UTC, okuzan commented on src/test/java/core/basesyntax/ReportServiceTest.java
> +    public void setStorage() {
```suggestion
    public void setup() {
```

2023-12-12 12:45 UTC, okuzan commented on src/test/java/core/basesyntax/ReportServiceTest.java
> +    public void createReport_validData() {
```suggestion
    public void createReport_validData_ok() {
```

2023-12-12 12:45 UTC, okuzan commented on src/test/java/core/basesyntax/PurchaseOperationHandlerTest.java
> +    public void process_validData_Ok() {
```suggestion
    public void process_validData_ok() {
```

2023-12-12 12:45 UTC, okuzan commented on src/test/java/core/basesyntax/ReportServiceTest.java
> +    public static void setReportService() {
unusual naming, fix everywhere

2023-12-12 12:45 UTC, okuzan commented on src/test/java/core/basesyntax/PurchaseOperationHandlerTest.java
> +    public void process_validData_Ok() {
let's check what happens if we try to purchase amount bigger than what we have in a storage. In other handlers, what happens if we pass a negative amount? FYI If you need to make changes to the code in /main, do it

2023-12-12 12:45 UTC, okuzan commented on src/test/java/core/basesyntax/ConversionServiceTest.java
> +    public void convert_validData_Ok() {
let's user lowercase after underscore everywhere

2023-12-12 12:45 UTC, okuzan commented on src/test/java/core/basesyntax/ConversionServiceTest.java
> +        List<String[]> validList = List.of(
we usually don't include data type in variable's name, Java is a strongly typed language, better call it validTransactions

2023-12-12 12:45 UTC, okuzan commented on src/test/java/core/basesyntax/ConversionServiceTest.java
> +                "Non-numeric data provided as quantity!");
having two same assertions on same method call is redundant

2023-12-12 12:45 UTC, okuzan commented on src/test/java/core/basesyntax/OperationStrategyTest.java
> +                new ReturnOperationHandler());
you can use Map.of

2023-12-13 15:15 UTC, Sanderfuck requested changes

2023-12-13 15:15 UTC, Sanderfuck commented on src/test/java/core/basesyntax/strategy/handler/BalanceOperationHandlerTest.java
> +    private static final String APPLE = "apple";
You don`t need to create same constants if you already have, lets reuse

2023-12-13 15:15 UTC, Sanderfuck commented on src/test/java/core/basesyntax/strategy/handler/PurchaseOperationHandlerTest.java
> +    private static final String APPLE = "apple";
The same

2023-12-13 15:15 UTC, Sanderfuck commented on src/test/java/core/basesyntax/strategy/handler/SupplyOperationHandlerTest.java
> +    private static final String APPLE = "apple";
```suggestion
 
```

2023-12-13 15:15 UTC, Sanderfuck commented on src/test/java/core/basesyntax/strategy/handler/ReturnOperationHandlerTest.java
> +    private static final String APPLE = "apple";
```suggestion
```

2023-12-14 10:59 UTC, kozhukhovsky approved these changes

2024-12-20 03:04 UTC, closed without merging