Tests for Fruit Shop Task
mate-academy/jv-fruit-shop-tests pull request #917
Opened 2024-03-12 12:01 UTC by DmitryLazyuka

2024-03-12 17:56 UTC, okuzan requested changes
Clean code, comprehensive testing 👏
Minor code style changes suggested
Add a test class for strategy too, what happens if there's no handler for some operation?

2024-03-12 17:56 UTC, okuzan commented on src/test/java/service/ReportGeneratorTest.java
> +        Map<String, Integer> data = Map.of("test1", 10,"test2",20);
```suggestion
        Map<String, Integer> data = Map.of("test1", 10, "test2", 20);
```
don't forget to auto format your files before committing with Ctrl Alt L

2024-03-12 17:56 UTC, okuzan commented on src/test/java/service/ReportGeneratorTest.java
> +    private static final String HEADING = "fruit,quantity";
```suggestion
    private static final String HEADER = "fruit,quantity";
```

2024-03-12 17:56 UTC, okuzan commented on src/test/java/service/FileServiceTest.java
> +    void writeToFile_cantCreatingFile_notOk() {
```suggestion
    void writeToFile_nonexistentPath_notOk() {
```
second part is about conditions under which test is executed, or about parameters that we pass, not about expected result (this is 3rd part)

2024-03-12 17:56 UTC, okuzan commented on src/test/java/service/FileServiceTest.java
> +    private static final String NON_EXISTING_FILE = "src/test/resources/non-existing-file.csv";
```suggestion
    private static final String NON_EXISTING_FILE = "invalid/path/to/non-existing-file.csv";
```
make it immediately obvious this is a dummy
also, there is no difference between an invalid path and non existing file - the result is that FileReader isn't able to find this file at this location

2024-03-12 17:56 UTC, okuzan commented on src/test/java/service/TransactionParserTest.java
> +    public void parse_illegalOperation_notOk() {
```suggestion
    void parse_illegalOperation_notOk() {
```

2024-03-13 10:46 UTC, okuzan requested changes

2024-03-13 10:46 UTC, okuzan commented on src/main/java/service/operation/OperationStrategyImpl.java
> +        }
```suggestion
            return handler;
```
no else after throwing/returning is needed

2024-03-13 10:46 UTC, okuzan commented on src/test/java/service/operation/OperationStrategyImplTest.java
> +
add _ok test too

2024-03-13 10:46 UTC, okuzan commented on src/test/java/service/operation/OperationStrategyImplTest.java
> +            Transaction.Operation.PURCHASE, new PurchaseOperation(new StorageDaoImpl()));
use one StorageDaoImpl

2024-03-13 10:46 UTC, okuzan commented on src/test/java/service/operation/OperationStrategyImplTest.java
> +
don't leave empty lines after method/class definition

2024-03-14 10:24 UTC, Vasul-Pankiv approved these changes

2026-06-04 08:13 UTC, closed without merging